### ISSUE TITLE
UTF8 text is not supported?

### ISSUE THREAD

**Issue by JoseHZBY** [evandroforks/SublimePackageGraphviz#1]
It seems that UTF8 text is not supported。

```graphviz
graph {
	图
}
```
and the error in console:
>[2020-03-24 11:56:51] - Lexical Error: line 2, column 1: token recognition error at: '图'

**Comment by JoseHZBY** [comment]
sorry, posted on run repo.

**Comment by evandrocoan** [comment]
What would be the right repository?

**Comment by JoseHZBY** [comment]
I was supposed to post the issue on `Graphvizer`，while just posted here, lol.
